### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by tmuellerchen** [Jonnobrow/spotify2m3u#2]
First: Great idea, it is exactly what I am looking for :)

I am a python noob ... so maybe I do something wrong ...

But when I start the script I get errors.

2022-04-29 23:08:53,875 - spotify2m3u.spotify2m3u.find_matches - INFO - Instatiating beets library
Traceback (most recent call last):
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/dbcore/db.py", line 1020, in _make_table
    rows = tx.query('PRAGMA table_info(%s)' % table)
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/dbcore/db.py", line 863, in query
    cursor = self.db._connection().execute(statement, subvals)
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/dbcore/db.py", line 947, in _connection
    conn = self._create_connection()
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/library.py", line 1439, in _create_connection
    conn = super(Library, self)._create_connection()
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/dbcore/db.py", line 961, in _create_connection
    conn = sqlite3.connect(
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/spotify2m3u/spotify2m3u/spotify2m3u/__main__.py", line 2, in <module>
    from spotify2m3u import find_matches, get_logger
  File "/root/spotify2m3u/spotify2m3u/spotify2m3u/find_matches.py", line 13, in <module>
    lib = beets.library.Library(beets_db_path, music_dir_path,
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/library.py", line 1430, in __init__
    super(Library, self).__init__(path, timeout=timeout)
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/dbcore/db.py", line 933, in __init__
    self._make_table(model_cls._table, model_cls._fields)
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/dbcore/db.py", line 1020, in _make_table
    rows = tx.query('PRAGMA table_info(%s)' % table)
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/dbcore/db.py", line 855, in __exit__
    self.db._connection().commit()
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/dbcore/db.py", line 947, in _connection
    conn = self._create_connection()
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/library.py", line 1439, in _create_connection
    conn = super(Library, self)._create_connection()
  File "/root/spotify2m3u/spotify2m3u/venv/lib/python3.9/site-packages/beets/dbcore/db.py", line 961, in _create_connection
    conn = sqlite3.connect(
sqlite3.OperationalError: unable to open database file

My config.yaml

auto_mode: False

paths:
  music_dir: /media/spotify/TEST
  beets_db: /root/library.db
  playlist_dir: /media/spotify/playlists/

credentials:
  CLIENT_ID: yakyakyak
  CLIENT_SECRET: yakyakyak

**Comment by Jonnobrow** [comment]
Hi, glad it's helpful :)

I would check a couple of things:
- Does the user running this python script have read permissions for the beets database?
- Where is the config file located? (Maybe it's still trying to load the default config)

If you want to try debugging it yourself, you can add some print statements in find_match.py near the top where the config is loaded.

Hope this helps, if not, let me know :)

**Comment by tmuellerchen** [comment]
Thank you very much. 
The config file was the point ... now I have made my change into config_default.yaml and it works.

:)

**Comment by Jonnobrow** [comment]
Fantastic. If you put a file named `config.yaml` in `$HOME/.config/spotify2m3u/` that should work too. I will close this issue now.
